CREATE TABLE IF NOT EXISTS bdu_vulns (
    bdu_id TEXT PRIMARY KEY,
    title TEXT,
    discovered_date DATE,
    severity TEXT,
    base_vector TEXT,
    crit_text TEXT,
    cve TEXT,
    status TEXT,
    recommendations TEXT,
    exploit_exists TEXT,
    exploitation_mode TEXT,
    elimination TEXT,
    infou TEXT,
    links JSONB,
    idvals JSONB,
    real_attack TEXT,
    consequences TEXT,
    publication_date DATE,
    update_date DATE,
    other_info TEXT,
    error_type TEXT,
    updated_at TIMESTAMP WITH TIME ZONE
)
